title: Deep Learning paper review
description: My Personal Stack Problems
author: Kim jaeyoung
github: https://github.com/kimjeyoung
about: Student of Gachon University, interested in Deep Learning and Python.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/kimjeyoung.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    
    - icon: fa-github
      link: "https://github.com/kimjeyoung"


urls:
    - text: About Me
      url: /about/
#    - text: Personal Project
#      url: /projects/


url: "https://kimjeyoung.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
